---
production: &base
  blob-storage-page-data-location: "s3:overview-production-page-data"
  blob-storage-file-contents-location: "s3:overview-production-file-contents"
  blob-storage-file-view-location: "s3:overview-production-file-view"
  canonical_host: www.overviewproject.org
  config_path: /opt/overview/config
  web_port: 9000
  google_analytics_id: "UA-34992611-1"
  managed_code_path: /opt/overview
  database_username: "overview"
  database_dbname: "overview"
  smtp_host: email-smtp.us-east-1.amazonaws.com
  smtp_port: 587
  smtp_ssl: true
  mail_from: 'no-reply@overviewproject.org'
  logger_smtp_from: 'server-error@overviewproject.org'
  logger_smtp_to: 'server-error@overviewproject.org'
  logger_smtp_subject_prefix: 'SERVER ERROR'
  logger_worker_smtp_subject_prefix: 'WORKER ERROR'
  redis_port: 6379
  es_cluster_name: overview-search-index
staging:
  <<: *base
  blob-storage-page-data-location: "s3:overview-staging-page-data"
  blob-storage-file-contents-location: "s3:overview-staging-file-contents"
  blob-storage-file-view-location: "s3:overview-staging-file-view"
  canonical_host: staging.overviewproject.org
  google_analytics_id: "UA-34992611-2"
